// Mock Data for Treatment Plans

import { TreatmentPlan } from './TreatmentPlan.types';

export const mockTreatmentPlans: TreatmentPlan[] = [
  {
    id: 'tp-001',
    case_book_id: 'cb-001',
    case_book_reference: 'CB-2026-001',
    prisoner_number: 'ARPC000000001/26',
    prisoner_name: 'John Doe',
    diagnosis_id: 'diag-001',
    diagnosis_name: 'Malaria with complications',
    prescribed_by: 'staff-001',
    prescribed_by_name: 'Dr. Sarah Mukasa',
    date_prescribed: '2026-02-06',
    treatment_status: 'Active',
    general_notes: 'Patient advised to rest, drink plenty of fluids, and return if symptoms worsen or fever persists after 3 days.',
    medications: [
      {
        id: 'med-001',
        medication_name: 'Artemether-Lumefantrine',
        medication_form: 'Tablet',
        is_quantifiable: true,
        quantity_dispensed: 48,
        dispensing_unit: 'Strip',
        dosage_quantity: '4',
        dosage_frequency: '3x daily',
        dosage_duration: 4,
        dosage_duration_unit: 'days',
        dosage_timing: 'After food',
        additional_instructions: 'Complete full course even if symptoms improve',
      },
      {
        id: 'med-002',
        medication_name: 'Paracetamol',
        medication_form: 'Tablet',
        is_quantifiable: true,
        quantity_dispensed: 20,
        dispensing_unit: 'Strip',
        dosage_quantity: '2',
        dosage_frequency: '2x daily',
        dosage_duration: 5,
        dosage_duration_unit: 'days',
        dosage_timing: 'As needed',
        additional_instructions: 'Take for fever or pain',
      },
      {
        id: 'med-003',
        medication_name: 'Vitamin C Syrup',
        medication_form: 'Syrup',
        is_quantifiable: true,
        quantity_dispensed: 200,
        dispensing_unit: 'Bottle',
        dosage_quantity: '10ml',
        dosage_frequency: '2x daily',
        dosage_duration: 7,
        dosage_duration_unit: 'days',
        dosage_timing: 'After food',
      },
    ],
    created_at: '2026-02-06T10:30:00Z',
  },
  {
    id: 'tp-002',
    case_book_id: 'cb-002',
    case_book_reference: 'CB-2026-002',
    prisoner_number: 'JMPR000000002/26',
    prisoner_name: 'Jane Smith',
    diagnosis_id: 'diag-002',
    diagnosis_name: 'Hypertension',
    prescribed_by: 'staff-002',
    prescribed_by_name: 'Dr. James Okello',
    date_prescribed: '2026-01-15',
    treatment_status: 'Active',
    general_notes: 'Monitor blood pressure weekly. Lifestyle modifications recommended: reduce salt intake, regular exercise. Patient responding well to medication.',
    medications: [
      {
        id: 'med-004',
        medication_name: 'Amlodipine',
        medication_form: 'Tablet',
        is_quantifiable: true,
        quantity_dispensed: 30,
        dispensing_unit: 'Strip',
        dosage_quantity: '1',
        dosage_frequency: '1x daily',
        dosage_duration: 30,
        dosage_duration_unit: 'days',
        dosage_timing: 'In the morning',
        additional_instructions: 'Take at same time each day',
      },
      {
        id: 'med-005',
        medication_name: 'Hydrochlorothiazide',
        medication_form: 'Tablet',
        is_quantifiable: true,
        quantity_dispensed: 30,
        dispensing_unit: 'Strip',
        dosage_quantity: '1',
        dosage_frequency: '1x daily',
        dosage_duration: 30,
        dosage_duration_unit: 'days',
        dosage_timing: 'In the morning',
      },
    ],
    created_at: '2026-01-15T14:20:00Z',
  },
  {
    id: 'tp-006',
    case_book_id: 'cb-006',
    case_book_reference: 'CB-2026-006',
    prisoner_number: 'JMPR000000002/26',
    prisoner_name: 'Jane Smith',
    diagnosis_id: 'diag-006',
    diagnosis_name: 'Malaria',
    prescribed_by: 'staff-001',
    prescribed_by_name: 'Dr. Sarah Mukasa',
    date_prescribed: '2025-08-12',
    treatment_status: 'Completed',
    general_notes: 'Patient responded well to treatment. All symptoms resolved after 5 days.',
    medications: [
      {
        id: 'med-012',
        medication_name: 'Artemether-Lumefantrine',
        medication_form: 'Tablet',
        is_quantifiable: true,
        quantity_dispensed: 24,
        dispensing_unit: 'Strip',
        dosage_quantity: '4',
        dosage_frequency: '2x daily',
        dosage_duration: 3,
        dosage_duration_unit: 'days',
        dosage_timing: 'After food',
        additional_instructions: 'Complete full course',
      },
      {
        id: 'med-013',
        medication_name: 'Paracetamol',
        medication_form: 'Tablet',
        is_quantifiable: true,
        quantity_dispensed: 10,
        dispensing_unit: 'Strip',
        dosage_quantity: '2',
        dosage_frequency: 'PRN (As needed)',
        dosage_timing: 'As needed',
        additional_instructions: 'For fever - max 3 times daily',
      },
    ],
    created_at: '2025-08-12T09:30:00Z',
  },
  {
    id: 'tp-007',
    case_book_id: 'cb-007',
    case_book_reference: 'CB-2026-007',
    prisoner_number: 'JMPR000000002/26',
    prisoner_name: 'Jane Smith',
    diagnosis_id: 'diag-007',
    diagnosis_name: 'Acute Gastritis',
    prescribed_by: 'staff-003',
    prescribed_by_name: 'Dr. Peter Ochieng',
    date_prescribed: '2025-11-20',
    treatment_status: 'Completed',
    general_notes: 'Advised to avoid spicy foods, caffeine, and alcohol. Patient educated on proper meal timing.',
    medications: [
      {
        id: 'med-014',
        medication_name: 'Omeprazole',
        medication_form: 'Capsule',
        is_quantifiable: true,
        quantity_dispensed: 14,
        dispensing_unit: 'Strip',
        dosage_quantity: '1',
        dosage_frequency: '1x daily',
        dosage_duration: 14,
        dosage_duration_unit: 'days',
        dosage_timing: 'Before food',
        additional_instructions: 'Take 30 minutes before breakfast',
      },
      {
        id: 'med-015',
        medication_name: 'Antacid Suspension',
        medication_form: 'Syrup',
        is_quantifiable: true,
        quantity_dispensed: 200,
        dispensing_unit: 'Bottle',
        dosage_quantity: '10ml',
        dosage_frequency: 'PRN (As needed)',
        dosage_timing: 'As needed',
        additional_instructions: 'Take when experiencing heartburn',
      },
    ],
    created_at: '2025-11-20T11:15:00Z',
  },
  {
    id: 'tp-003',
    case_book_id: 'cb-003',
    case_book_reference: 'CB-2026-003',
    prisoner_number: 'MKPR000000003/26',
    prisoner_name: 'Michael Johnson',
    diagnosis_id: 'diag-003',
    diagnosis_name: 'Respiratory Tract Infection',
    prescribed_by: 'staff-001',
    prescribed_by_name: 'Dr. Sarah Mukasa',
    date_prescribed: '2026-02-04',
    treatment_status: 'Active',
    general_notes: 'Avoid cold drinks. Use steam inhalation twice daily.',
    medications: [
      {
        id: 'med-006',
        medication_name: 'Amoxicillin',
        medication_form: 'Capsule',
        is_quantifiable: true,
        quantity_dispensed: 21,
        dispensing_unit: 'Strip',
        dosage_quantity: '1',
        dosage_frequency: '3x daily',
        dosage_duration: 7,
        dosage_duration_unit: 'days',
        dosage_timing: 'After food',
        additional_instructions: 'Complete full course',
      },
      {
        id: 'med-007',
        medication_name: 'Bromhexine Syrup',
        medication_form: 'Syrup',
        is_quantifiable: true,
        quantity_dispensed: 100,
        dispensing_unit: 'Bottle',
        dosage_quantity: '10ml',
        dosage_frequency: '3x daily',
        dosage_duration: 5,
        dosage_duration_unit: 'days',
        dosage_timing: 'After food',
      },
    ],
    created_at: '2026-02-04T09:15:00Z',
  },
  {
    id: 'tp-004',
    case_book_id: 'cb-004',
    case_book_reference: 'CB-2026-004',
    prisoner_number: 'EDPR000000004/26',
    prisoner_name: 'Emily Davis',
    diagnosis_id: 'diag-004',
    diagnosis_name: 'Type 2 Diabetes Mellitus',
    prescribed_by: 'staff-003',
    prescribed_by_name: 'Dr. Peter Ochieng',
    date_prescribed: '2026-02-03',
    treatment_status: 'Active',
    general_notes: 'Blood sugar monitoring required. Diet modifications discussed.',
    medications: [
      {
        id: 'med-008',
        medication_name: 'Metformin',
        medication_form: 'Tablet',
        is_quantifiable: true,
        quantity_dispensed: 60,
        dispensing_unit: 'Strip',
        dosage_quantity: '1',
        dosage_frequency: '2x daily',
        dosage_duration_unit: 'ongoing',
        dosage_timing: 'With food',
        additional_instructions: 'Take with meals to reduce stomach upset',
      },
      {
        id: 'med-009',
        medication_name: 'Glibenclamide',
        medication_form: 'Tablet',
        is_quantifiable: true,
        quantity_dispensed: 30,
        dispensing_unit: 'Strip',
        dosage_quantity: '1',
        dosage_frequency: '1x daily',
        dosage_duration_unit: 'ongoing',
        dosage_timing: 'Before food',
        additional_instructions: 'Take 30 minutes before breakfast',
      },
    ],
    created_at: '2026-02-03T11:45:00Z',
  },
  {
    id: 'tp-005',
    case_book_id: 'cb-005',
    case_book_reference: 'CB-2026-005',
    prisoner_number: 'RLPR000000005/26',
    prisoner_name: 'Robert Lee',
    diagnosis_id: 'diag-005',
    diagnosis_name: 'Acute Gastritis',
    prescribed_by: 'staff-002',
    prescribed_by_name: 'Dr. James Okello',
    date_prescribed: '2026-02-02',
    treatment_status: 'Completed',
    general_notes: 'Avoid spicy foods and alcohol. Follow up if symptoms persist.',
    medications: [
      {
        id: 'med-010',
        medication_name: 'Omeprazole',
        medication_form: 'Capsule',
        is_quantifiable: true,
        quantity_dispensed: 14,
        dispensing_unit: 'Strip',
        dosage_quantity: '1',
        dosage_frequency: '1x daily',
        dosage_duration: 14,
        dosage_duration_unit: 'days',
        dosage_timing: 'Before food',
        additional_instructions: 'Take in the morning before breakfast',
      },
      {
        id: 'med-011',
        medication_name: 'Antacid Suspension',
        medication_form: 'Syrup',
        is_quantifiable: true,
        quantity_dispensed: 200,
        dispensing_unit: 'Bottle',
        dosage_quantity: '10ml',
        dosage_frequency: 'PRN (As needed)',
        dosage_timing: 'As needed',
        additional_instructions: 'Take when experiencing heartburn',
      },
    ],
    created_at: '2026-02-02T16:00:00Z',
  },
];

// Mock Case Books for dropdown
export const mockCaseBooks = [
  {
    id: 'cb-001',
    reference: 'CB-2026-001',
    prisoner_number: 'ARPC000000001/26',
    prisoner_name: 'John Doe',
    diagnoses: ['Malaria with complications', 'Influenza (Flu)', 'Upper Respiratory Tract Infection', 'Anaemia'],
  },
  {
    id: 'cb-002',
    reference: 'CB-2026-002',
    prisoner_number: 'JMPR000000002/26',
    prisoner_name: 'Jane Smith',
    diagnoses: ['Hypertension'],
  },
  {
    id: 'cb-003',
    reference: 'CB-2026-003',
    prisoner_number: 'MKPR000000003/26',
    prisoner_name: 'Michael Johnson',
    diagnoses: ['Respiratory Tract Infection', 'Cough'],
  },
];

// Mock Medications for autocomplete
export const mockMedications = [
  'Paracetamol',
  'Artemether-Lumefantrine',
  'Amoxicillin',
  'Metformin',
  'Amlodipine',
  'Omeprazole',
  'Vitamin C Syrup',
  'Bromhexine Syrup',
  'Hydrochlorothiazide',
  'Glibenclamide',
  'Ibuprofen',
  'Ciprofloxacin',
  'Diclofenac',
  'Atorvastatin',
  'Aspirin',
];




